### ISSUE TITLE
Not providing the preloadPagesCount throw an Exception

### ISSUE THREAD

**Issue by wrbl606** [Neil-Gu/preload_page_view#3]
When you update the library from 0.1.2 to 0.1.3 and you'll not provide the new `preloadPagesCount` property, widget will throw an exception:

```logcat
I/flutter (28504): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (28504): The following NoSuchMethodError was thrown building Scrollable(axisDirection: right, physics:
I/flutter (28504): PageScrollPhysics, dirty, dependencies: [_LocalizationsScope-[GlobalKey#d9d95], _InheritedTheme,
I/flutter (28504): ScrollConfiguration], state: ScrollableState#cda16(position: _PagePosition#c976f(offset: null,
I/flutter (28504): range: null..null, viewport: null, ScrollableState, PageScrollPhysics -> ClampingScrollPhysics,
I/flutter (28504): IdleScrollActivity#f9ea2, ScrollDirection.idle))):
I/flutter (28504): The method '<=' was called on null.
I/flutter (28504): Receiver: null
I/flutter (28504): Tried calling: <=(1)
I/flutter (28504): 
I/flutter (28504): When the exception was thrown, this was the stack:
I/flutter (28504): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter (28504): #1      _PreloadPageViewState.build.<anonymous closure> (package:preload_page_view/preload_page_view.dart:554:45)
I/flutter (28504): #2      ScrollableState.build (package:flutter/src/widgets/scrollable.dart:551:27)
I/flutter (28504): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
I/flutter (28504): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3736:15)
I/flutter (28504): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (28504): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (28504): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (28504): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (28504): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (28504): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (28504): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (28504): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (28504): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (28504): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (28504): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (28504): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (28504): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (28504): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (28504): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (28504): #20     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (28504): #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (28504): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (28504): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (28504): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (28504): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (28504): #26     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
I/flutter (28504): #27     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (28504): #28     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
I/flutter (28504): #29     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter (28504): #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
I/flutter (28504): #31     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
I/flutter (28504): #35     _invoke (dart:ui/hooks.dart:209:10)
I/flutter (28504): #36     _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter (28504): (elided 3 frames from package dart:async)
I/flutter (28504): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

I suggest assigning `preloadPagesCount` some default value. I think `1` will be ok. When we agree to some default value I'll happy to create a pull request with this change.

**Comment by Neil-Gu** [comment]
That's my bad, I didn't put a default value to `preloadPagesCount`, it will be great if you could create the PR
